%%%%%%%%%% autogenerated code follows;
handle_command("init_location", Parameters, State) ->
    % implementation for init_location,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [Locname,Height,Floorlevel,Preference,Attributes] = Tokens,
    NewLocname = mypl_util:convertString(Locname),
    NewHeight = mypl_util:convertPositiveInteger(Height),
    NewFloorlevel = mypl_util:convertBoolean(Floorlevel),
    NewPreference = mypl_util:convertPositiveInteger(Preference),
    NewAttributes = mypl_util:convertArray(Attributes),
    {noreply, reply(220, rfc4627:encode(mypl_server:init_location(NewLocname,NewHeight,NewFloorlevel,NewPreference,NewAttributes)), reset_buffers(State))};
handle_command("location_info", Parameters, State) ->
    % implementation for location_info,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [Locname] = Tokens,
    NewLocname = mypl_util:convertString(Locname),
    {noreply, reply(220, rfc4627:encode(mypl_server:location_info(NewLocname)), reset_buffers(State))};
handle_command("location_list", Parameters, State) ->
    % implementation for location_list,
    {noreply, reply(220, rfc4627:encode(mypl_server:location_list()), reset_buffers(State))};
handle_command("store_at_location", Parameters, State) ->
    % implementation for store_at_location,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [Locname,Mui,Quantity,Product,Height] = Tokens,
    NewLocname = mypl_util:convertString(Locname),
    NewMui = mypl_util:convertString(Mui),
    NewQuantity = mypl_util:convertPositiveInteger(Quantity),
    NewProduct = mypl_util:convertString(Product),
    NewHeight = mypl_util:convertPositiveInteger(Height),
    {noreply, reply(220, rfc4627:encode(mypl_server:store_at_location(NewLocname,NewMui,NewQuantity,NewProduct,NewHeight)), reset_buffers(State))};
handle_command("retrive", Parameters, State) ->
    % implementation for retrive,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [Mui] = Tokens,
    NewMui = mypl_util:convertString(Mui),
    {noreply, reply(220, rfc4627:encode(mypl_server:retrive(NewMui)), reset_buffers(State))};
handle_command("init_movement", Parameters, State) ->
    % implementation for init_movement,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [Mui,Locname] = Tokens,
    NewMui = mypl_util:convertString(Mui),
    NewLocname = mypl_util:convertString(Locname),
    {noreply, reply(220, rfc4627:encode(mypl_server:init_movement(NewMui,NewLocname)), reset_buffers(State))};
handle_command("init_movement_to_good_location", Parameters, State) ->
    % implementation for init_movement_to_good_location,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [Mui] = Tokens,
    NewMui = mypl_util:convertString(Mui),
    {noreply, reply(220, rfc4627:encode(mypl_server:init_movement_to_good_location(NewMui)), reset_buffers(State))};
handle_command("commit_movement", Parameters, State) ->
    % implementation for commit_movement,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [MovementId] = Tokens,
    NewMovementId = mypl_util:convertString(MovementId),
    {noreply, reply(220, rfc4627:encode(mypl_server:commit_movement(NewMovementId)), reset_buffers(State))};
handle_command("rollback_movement", Parameters, State) ->
    % implementation for rollback_movement,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [MovementId] = Tokens,
    NewMovementId = mypl_util:convertString(MovementId),
    {noreply, reply(220, rfc4627:encode(mypl_server:rollback_movement(NewMovementId)), reset_buffers(State))};
handle_command("init_pick", Parameters, State) ->
    % implementation for init_pick,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [Quantity,Mui] = Tokens,
    NewQuantity = mypl_util:convertPositiveInteger(Quantity),
    NewMui = mypl_util:convertString(Mui),
    {noreply, reply(220, rfc4627:encode(mypl_server:init_pick(NewQuantity,NewMui)), reset_buffers(State))};
handle_command("commit_pick", Parameters, State) ->
    % implementation for commit_pick,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [PickId] = Tokens,
    NewPickId = mypl_util:convertString(PickId),
    {noreply, reply(220, rfc4627:encode(mypl_server:commit_pick(NewPickId)), reset_buffers(State))};
handle_command("rollback_pick", Parameters, State) ->
    % implementation for rollback_pick,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [PickId] = Tokens,
    NewPickId = mypl_util:convertString(PickId),
    {noreply, reply(220, rfc4627:encode(mypl_server:rollback_pick(NewPickId)), reset_buffers(State))};
handle_command("count_product", Parameters, State) ->
    % implementation for count_product,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [Product] = Tokens,
    NewProduct = mypl_util:convertString(Product),
    {noreply, reply(220, rfc4627:encode(mypl_server:count_product(NewProduct)), reset_buffers(State))};
handle_command("count_products", Parameters, State) ->
    % implementation for count_products,
    {noreply, reply(220, rfc4627:encode(mypl_server:count_products()), reset_buffers(State))};
handle_command("find_provisioning_candidates", Parameters, State) ->
    % implementation for find_provisioning_candidates,
    Tokens = lists:map(fun(X) -> string:strip(X) end, string:tokens(Parameters, [$,])),
    [Quantity,Product] = Tokens,
    NewQuantity = mypl_util:convertPositiveInteger(Quantity),
    NewProduct = mypl_util:convertString(Product),
    {noreply, reply(220, rfc4627:encode(mypl_server:find_provisioning_candidates(NewQuantity,NewProduct)), reset_buffers(State))};

handle_command("help", _Parameters, State) -> {noreply, reply(220, "Help follows:
init_location Locname,Height,Floorlevel,Preference,Attributes
location_info Locname
location_list 
store_at_location Locname,Mui,Quantity,Product,Height
retrive Mui
init_movement Mui,Locname
init_movement_to_good_location Mui
commit_movement MovementId
rollback_movement MovementId
init_pick Quantity,Mui
commit_pick PickId
rollback_pick PickId
count_product Product
count_products 
find_provisioning_candidates Quantity,Product", reset_buffers(State))};
handle_command("quit", _ClientDomain, State) -> {stop, normal, reply(201, "Goodbye", reset_buffers(State))};
handle_command(Command, _Parameters, State) -> {noreply, reply(500, "Unsupported command " ++ Command, State)}.

%%%%%%%%%% autogenerated code ends
